### ISSUE TITLE
[ADD] Weather App

### ISSUE THREAD

**Issue by Anadee11** [Anadee11/WebArena#12]

**Comment by itzwow** [comment]
I would love to work on this issue
Kindly assign it to me

**Comment by Anadee11** [comment]
Definitely go for it! Please remember to add a readme to your project.

**Comment by Uttkarrsh** [comment]
As this issue has not been resolved can I work on it?

**Comment by Anadee11** [comment]
@Uttkarrsh I have assigned this issue already. Feel free to create any new issues and would be more than happy to assign it to you!

**Comment by Uttkarrsh** [comment]
@Anadee11 can I add a Rock Paper Scissor Game built in HTML CSS Javascript?

**Comment by Anadee11** [comment]
Yes @Uttkarrsh create a new issue for it and you are good to go!

**Comment by Anadee11** [comment]
Thank you for contributing @itzwow. Do support us by leaving a star ⭐ on the repository.
