### ISSUE TITLE
[ADD] Basic Web Server in Go

### ISSUE THREAD

**Issue by jayeshmann** [Anadee11/WebArena#20]
I believe, Arena can make use of a web server and for higher performance, Go is preferred.

**Comment by Anadee11** [comment]
Yes go for it! Make sure to add a readme.md file in your project. 
Also, there would be a connected frontend with the server right??

**Comment by Anadee11** [comment]
Thank you for contributing @jayeshmann. Do support us by leaving a star ⭐ on the repository.
