### ISSUE TITLE
[ADD] Random Joke Generator

### ISSUE THREAD

**Issue by Anadee11** [Anadee11/WebArena#36]
- [ ] Add a readme.md file to your project.
- [x] This issue was opened after seeing the issues and so no similar issues are present.

**Comment by SahilChandravanshi** [comment]
Hey @Anadee11 , please assign this to me. I'd like to work on this.

**Comment by ShivamPande18** [comment]
Hey @Anadee11 I would like to contribute on this project.

**Comment by Anadee11** [comment]
Hey! @SahilChandravanshi. Go for it.
- [ ] Add a readme.md file to your project.
- [ ] This issue was opened after seeing the issues and so no similar issues are present.

**Comment by Anadee11** [comment]
Hey @ShivamPande18 .
Actually this issue has been assigned and Sahil is working on it.
Feel free to open any new issue and I'll surely assign it to you!

**Comment by SahilChandravanshi** [comment]
Thanks for assigning. Working on it.

**Comment by SahilChandravanshi** [comment]
Hey @Anadee11 , Please review my PR.

**Comment by Anadee11** [comment]
Thank you for contributing @SahilChandravanshi. Do support us by leaving a star ⭐ on the repository.
