### ISSUE TITLE
[ADD] Wordtyping-game 

### ISSUE THREAD

**Issue by meetkool** [Anadee11/WebArena#38]
- [x] Add a readme.md file to your project.
- [x] This issue was opened after seeing the issues and so no similar issues are present.

**Comment by Anadee11** [comment]
- [ ] Add a readme.md file to your project.
- [ ] This issue was opened after seeing the issues and so no similar issues are present.

**Comment by meetkool** [comment]
i uploaded the readme

**Comment by Anadee11** [comment]
Thank you for contributing @meetkool. Do support us by leaving a star ⭐ on the repository.
