### ISSUE TITLE
[ADD] Random Text / Number / Avatar Generator

### ISSUE THREAD

**Issue by Anadee11** [Anadee11/WebArena#40]
- [ ] Add a readme.md file to your project.
- [x] This issue was opened after seeing the issues and so no similar issues are present.

**Comment by Uttkarrsh** [comment]
Hey Can I add Random Number Generator Program?

**Comment by Anadee11** [comment]
Go for it!

**Comment by Anadee11** [comment]
Thank you for contributing @Uttkarrsh. Do support us by leaving a star ⭐ on the repository.
