### ISSUE TITLE
[ADD] Food Ordering Website

### ISSUE THREAD

**Issue by Anadee11** [Anadee11/WebArena#5]

**Comment by SrishtiDharwani** [comment]
@Anadee11 can I work on this?

**Comment by Anadee11** [comment]
Hey @SrishtiDharwani. Thank you for the contribution. Do leave a star ⭐ on the repository to support. Happy Contributing!

**Comment by SrishtiDharwani** [comment]
Sure @Anadee11 , Happy to contribute!
