### ISSUE TITLE
[ADD] Portfolio Website using React

### ISSUE THREAD

**Issue by Anadee11** [Anadee11/WebArena#7]

**Comment by chetan-2002** [comment]
Hey ,can I add my portfolio website to this issue ?

**Comment by Anadee11** [comment]
Hey go for it! Make sure you have used React as the framework. Also, please add a readme file to your project.

**Comment by Anadee11** [comment]
Thank you for contributing @chetan-2002. Do support us by leaving a star ⭐ on the repository.
